SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME
FROM ANIMAL_INS AS A
JOIN ANIMAL_OUTS AS B
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE NOT (
    A.SEX_UPON_INTAKE LIKE 'Spayed%' 
    OR A.SEX_UPON_INTAKE LIKE 'Neutered%'
)
AND (
    B.SEX_UPON_OUTCOME LIKE 'Spayed%' 
    OR B.SEX_UPON_OUTCOME LIKE 'Neutered%'
)
ORDER BY A.ANIMAL_ID